export enum ComputingType {
    RECOMMENDATION_TYPE = 'RECOMMENDATION',
    SAFETY_TYPE = 'SAFETY',
    STAIRS_TYPE = 'STAIRS',
    ESCALATOR_TYPE = 'ESCALATOR',
    ELEVATOR_TYPE = 'ELEVATOR',
    OTHER_TYPE = 'OTHER',
}
